export default {
  'menu.profile': '管理多账户',
  'userInfo.addProfile': '新增 Profile',
  'userInfo.myProfiles': '我的 Profiles',
  'myProfiles.isDelete': '确认删除？',
  'myProfiles.modal.ok': '确定',
  'myProfiles.modal.cancel': '取消',
  'myProfiles.popconfirm.content': '确认删除？',
  'myProfiles.profileCard.checkAwards': '检查是否中奖',
  'myProfiles.profileCard.addAccount': '增加账号',
  'myProfiles.modal.editProfile.title': '编辑 Profile',
  'myProfiles.modal.editProfile.name': 'Profile 名称',
  'myProfiles.modal.editProfile.submit': '保存',
  'myProfiles.dropdown.optoin.delete': '删除',
  'myProfiles.dropdown.optoin.edit': '修改',
  'myProfiles.modal.addProfile.rule.required': '名称是必输的',
  'myProfiles.modal.addProfile.placehoder.profileName': '请输入名称...',
  'myProfiles.modal.addAccount.rule.required': '账号是必输的',
  'myProfiles.modal.addAccount.rule2.required':
    '账号必须是44个字母/数字，也许前后存在空格...',
  'myProfiles.modal.addAccount.rule3.required':
    '地址应该是一个 terra 地址，也许前后存在空格...',
  'myProfiles.modal.addProfile.placehoder.account': '请输入你的账号地址...',
  'myProfiles.modal.addAccount.label': '账号',
};
